# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'Voicutter' do
pod 'EZAudio', '~> 1.1.2'
end

target 'VoicutterTests' do

end

target 'VoicutterUITests' do

end

